export const T = {
  bg: 'var(--bg)',
  card: 'var(--card)',
  card2: 'var(--card2)',
  card3: 'var(--card3)',
  bdr: 'var(--bdr)',
  bdr2: 'var(--bdr2)',
  txt: 'var(--txt)',
  mute: 'var(--mute)',
  sub: 'var(--sub)',
  AMB: 'var(--AMB)',
  ambDim: 'var(--ambDim)',
  BLU: 'var(--BLU)',
  bluDim: 'var(--bluDim)',
  GRN: 'var(--GRN)',
  grnDim: 'var(--grnDim)',
  RED: 'var(--RED)',
  redDim: 'var(--redDim)',
  PUR: 'var(--PUR)',
  purDim: 'var(--purDim)',
  ORG: 'var(--ORG)',
  orgDim: 'var(--orgDim)',
};
